<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PhlyPaste\Module'                     => __DIR__ . '/Module.php',
    'PhlyPaste\Controller\PasteController' => __DIR__ . '/src/PhlyPaste/Controller/PasteController.php',
    'PhlyPasteTest\Bootstrap'              => __DIR__ . '/test/Bootstrap.php',
);
