<section class="phly-paste row">
<div class="span8">
    <h1>Help</h1>

    <ul>
        <li><a href="#general">General</a></li>
        <li><a href="#advanced">Advanced Pasting</a></li>
        <li><a href="#api">API</a></li>
    </ul>

    <br />

    <h2 id="general">General</h2>

        <p>
            This is a pastebin application, intended for sharing and discussing 
            code. Paste some code in, and then share the URL provided to you.
            This is particularly useful on IRC, where you typically do not want
            to paste large sections of code.
        </p>

        <p>
            Pastes are limited to 64k.
        </p>

    <h2 id="advanced">Advanced Pasting</h2>
    
        <h3>Sections</h3>

        <p>
            You can divide a paste into multiple sections, typically to 
            represent different files you wish to share. To create a 
            new section, start a line with "##", and include 1 or more
            lines following it. Any text following the "##" will be used
            as the section title.
        </p>

        <pre class="well">
## first.txt
This is the first file.

## second.txt
This is the second file.
        </pre>

    <h3>Section-specific syntax highlighting</h3>
        
        <p>
            Chances are, if you're representing multiple files in your paste,
            you may have multiple languages represented. You can indicate the
            language to use for syntax highlighting in braces (<code>[ ]</code>)
            following the filename/section title.
        </p>

        <pre class="well">
## composer.json [javascript]
{
    "require": {
        "phly/phly-paste": "dev-master"
    }
}
## config/application.config.php [php]
return array(
    'modules' => array(
        'Application',
        'PhlyPaste',
    ),
    /* ... */
);
        </pre>

    <h2 id="api">API</h2>

        <p>
            A RESTful JSON API is provided by default, and is found at the path 
            <code>/paste/api/paste</code>. It uses the <code>application/hal+json</code>
            media type, and allows listing, fetching, and submitting pastes, as 
            detailed below.
        </p>

        <h3>GET /paste/api/paste[?page=X]</h3>

        <p>
            Retrieves a single page of a list of pastes. The payload looks like the
            following:
        </p>

        <pre>
HTTP/1.0 200 Ok
Content-Type: application/hal+json

{
    "_links": {
        "canonical": {"rel": "canonical", "href": "http://pages.local/paste"},
        "self": {"rel": "self", "href": "http://pages.local/paste/api/paste"},
        "first": {"rel": "first", "href": "http://pages.local/paste/api/paste"},
        "last": {"rel": "last", "href": "http://pages.local/paste/api/paste?page=X"},
        "next": {"rel": "next", "href": "http://pages.local/paste/api/paste?page=2"}
    },
    "items": [
        [
            {"rel": "canonical", "href": "http://pages.local/paste/XYZ"},
            {"rel": "item", "href": "http://pages.local/paste/api/paste/XYZ"}
        ],
        /* ... */
    ]
}
        </pre>

        <h3>GET /paste/api/paste/XYZ12ABC</h3>
        
        <p>
            Fetches information on a single paste. The payload looks like the 
            following:
        </p>

        <pre>
HTTP/1.0 200 Ok
Content-Type: application/hal+json

{
    "_links": {
        "canonical": {"rel": "canonical", "href": "http://pages.local/paste/XYZ12ABC"},
        "self": {"rel": "self", "href": "http://pages.local/paste/api/paste/XYZ12ABC"},
        "up": {"rel": "up", "href": "http://pages.local/paste/api/paste"}
    },
    "title": "...",
    "language": "...",
    "timestamp": "...",
}
        </pre>

        <h3>POST /paste/api/paste</h3>

        <p>
            Creates a new paste. This requires that you have an API token; ask 
            the administrator of this site for one if you need this functionality.
        </p>

        <h4>Body as JSON</h4>

        <p>
            Expects a JSON body, like the following:
        </p>

        <pre>
Accept: application/hal+json
Content-Type: application/hal+json
X-PhlyPaste-Token: yourtoken

{
    "language": "txt",
    "private": "false",
    "content": "This is the paste content..."
}
        </pre>

        <p>
            You will get the following response payload:
        </p>

        <pre>
HTTP/1.0 201 Created
Location: http://paste.local/paste/XYZ12ABC
Content-Type: application/hal+json

{
    "_links": {
        "canonical": {"rel": "canonical", "href": "http://pages.local/paste/XYZ12ABC"},
        "self": {"rel": "self", "href": "http://pages.local/paste/api/paste/XYZ12ABC"}
    }
}
        </pre>

        <h4>Body as content</h4>

        <p>
            Alternately, you can provide the paste as the request content, and 
            specify the language and private status via the query string.
        </p>

        <pre>
POST /paste/api/paste?language=text&private=false
Accept: application/hal+json
Content-Type: text/plain
X-PhlyPaste-Token: yourtoken

This is the paste content...
        </pre>

        <p>
            The response payload is exactly the same as the previous example.
        </p>

        <h3>GET /paste/api/languages</h3>

        <p>
            Returns a list of language strings that may be used when creating a paste.
        </p>

        <pre>
HTTP/1.0 200 Ok
Content-Type: application/hal+json

{
    "languages": [
        "apache",
        "diff",
        "html4strict",
        "ini",
        "javascript",
        "jquery",
        "markdown",
        "php",
        "text",
        "python",
        "ruby",
        "bash",
        "sql",
        "vim",
        "xml"
    ]
}
        </pre>
</div>

<?php echo $this->render('phly-paste/paste/sidebar'); ?>

</section>
