<figure>
    <figcaption>
        <span class="left span4">
            <a href="<?php echo $this->url('phly-paste/view', array('paste' => $paste->hash)) ?>">View</a>
            <?php
                $lines = $this->numberOfLines($paste->content);
                if (!empty($lines)) {
                    echo '&nbsp;&nbsp;' . $lines;
                }
            ?>
        </span>
        <span class="right span4">
            <?php echo $this->timeAgo($paste->timestamp) ?> ago
        </span>
    </figcaption>

    <pre><code><?php echo $this->escapeHtml(substr($this->paste->content, 0, 100)) ?></code></pre>
</figure>
