<article class="row">
<div class="span8">
    <?php /** 
           * @todo helper for marking up pastes 
           */ ?>
    <pre><?php echo $this->escapeHtml($this->paste->content) ?></pre>
    
    <dl>
        <dt>Pasted</dt>
        <dd><?php echo $this->timeAgo($this->paste->timestamp) ?></dd>

        <dt>Embed</dt>
        <dd><input type="text" value="&lt;script src='http://<?php echo $_SERVER['SERVER_NAME'] . $this->url('phly-paste/view/embed', array('paste' => $this->paste->hash)) ?>'&gt;&lt;/script&gt;"/></dd>

        <?php /** 
               * @todo links for raw and repaste 
               */ ?>
        <dt>Act</dt>
        <dd><a href="<?php echo $this->url('phly-paste/view/raw', array('paste' => $paste->hash)) ?>">Raw</a></dd>
        <dd><a href="<?php echo $this->url('phly-paste/view/repaste', array('paste' => $paste->hash)) ?>">Repaste</a></dd>
    </dl>
</div>

<?php echo $this->render('phly-paste/paste/sidebar') ?>

</article>

