<article>
    <?php /** 
           * @todo helper for marking up pastes 
           */ ?>
    <div class="example"><pre><code><?php echo $this->escapeHtml($this->paste->content) ?></code></pre></div>
    
    <dl>
        <dt>Pasted</dt>
        <dd><?php echo $this->timeAgo($this->paste->timestamp) ?></dd>

        <dt>Embed</dt>
        <dd><input type="text" value="&lt;script src='http://<?php echo $_SERVER['SERVER_NAME'] . $this->url('phly-paste/view/embed', array('paste' => $this->paste->hash)) ?>'&gt;&lt;/script&gt;"/></dd>

        <?php /** 
               * @todo links for raw and repaste 
               */ ?>
        <dt>Act</dt>
        <dd>Raw</dd>
        <dd><a href="<?php echo $this->url('phly-paste/view/repaste', array('paste' => $paste->hash)) ?>">Repaste</a></dd>
    </dl>
</article>

